import type { Metadata } from "next";
import "./globals.css";

import { Kranky } from "next/font/google";

export const kranky = Kranky({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "JHONATHAN | PORTIFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kranky.className} antialiased`}>{children}</body>
    </html>
  );
}
