import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import "./globals.css";

import { Kranky } from "next/font/google";

export const kranky = Kranky({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "JHONATHAN | PORTIFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kranky.className}`}>
        <ThemeProvider attribute="class">
          <Header />
          <div className="h-[1px] w-full bg-line-light dark:bg-line-dark"></div>
          <div className="mx-[22px] min-h-screen border-x border-line-light dark:border-line-dark">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
